a = 'TTCTTAATTAAAGTGTATATAATTAAGTGCATGGCGTATAGGCACATCTGAGACGCCGCTTGTGGCATTGAAAAGCAGAACAAGTCCGTGCTTTTACAGCGGTCTGCAGATCTTTAACCCGTCGTATGTCTTGGTGCCAAAGCGGAGTACTAGGGATAACGCGCCTGCCTGTATCCAGCGAATGACCCCTCGAGACCTACCTACCGGTGGATCCAGCGAATGAGTCCAGCGCGTATCTCTCGTGGACCAATTCCGAAAGAAACGCCCCGTGGGCAATATCTTCAGATTAGTTAGCACGTGGACGTCGTTAGTTCTAGTTACTCGGTTGGGAAGTATCGCCAGCCACTGTAACATTTTGTGCCCCCAACGTTCGCGGGTTTCATAACACAGTGCCATTTTATTGATCGTTTCGACAGACTCTTCAGGTCTTAAATTATGCGTCGAGGTATGTCTCTCGGACACGATTCCCTCCTTTCACCCCCTCGGGCCGTAATGCAGAAAAGCAGCACAATGCTAACACGGTCATATAACATGGCACGGGTAGTGGCGAAATCTTGCCAGTATACCTGCGGAGCGCCGCTAGGACTTCGCACTGCCTAGACTGACGTGCTAGCTTCGCATGTGTTGAGACGCGTCGGCCTGAGACCGATCAATTGGTATGTTAAGATCTGAACTTAAGCCCCGGTTGATCAGATTCCGGGTCGCTGATATCCTACCCTTAGGGAGCCATTTCCGTCTGCGCTCAAACTCTTGAGGGCAGACGCAGACCGCTAATCTAGAAGGGGGCCGCATGCTCAGTGTTCCCGATCCGTCTACAACGGAGGCTACGGTGAAGTCCTCAGCCGTTACCCTTGTTA'

def reverse_complement_dna(a):
    b = ''
    r = []
    for letter in a:
        if letter == 'A':
            r.append('T')
        elif letter == 'T':
            r.append('A')
        elif letter == 'C':
            r.append('G')
        else:
            r.append('C')
    r.reverse()
    return b.join(r)


print(reverse_complement_dna(a))