seq1='GTTATCGCGGAAAATGGCCCTGTGAGGCTGCGTTTCATTAGCTTGACGCCGTATGGGATGGTGGGAACTATGTAAAGTAATACTGTGTTCATGTAATGAACGACGACCCAACAGCTGATTAATTATTGGTATTTATGACCATTCGTTCCCTTCATGGGAGAAGACAACGGGTAAAGGGCGCGATATCCCGTTGCGGTCCGTAACTGCCCTAGCTCGGTCCCACGGAGGTGCGCCTTTCTAGCGATCACACAGTCAGGAGATCACAGAAGTCCATGTCCCCTGTGTCACCGGGAGTAGGAGAAATGCCTCCTAGTTCAAGCCGGTGGAGCCTGTTAAGCCGTTAAAGATCTGACAACCGAGAGTCAAATTGTACTGTTCGTATTTAAGGGGGTCGTCCGGATCCGAACGCCTAGTACTCCATCCACACCAGTAAAAGACGGGATGAGTCCGCATACCAGGGCCAAAGCCCTGTACAATGCAATGAAACGTCTTGTTTCCGTGTCGGGGAGGTGCGTCCTACCCCGTAATCTCCGTCCGTCGGGGCCATTATCGCTGCTTGCCTTTTATGTTAACAGATGCTATCTCAGATATCGGTTCATGGGTCTGGGCCGGCATTCATAACAGACTTGCGTGTAGGCGAACTGACGTGTATAGATCAGAGTAGGGACCAAGTTTGACCATACCTCGGGGGTTACATGCGCCTGGACTTGCGATATCAGTCCTTCCTGTTATTTGCGATAGCCGCAAGCGCAAAGTCCGAACCGTACCAGTACACATCTCTTACCTGATTGAGTAGATAAAAGTTAACTAGTCCTTCATAGCAAGCTGTACTACATGCGGGGTGGAACCGTGAGACAAATCGGCTTCCCGGTCGAGGAAGTGATCCCTGGGCG'
seq2='GTTATTACGGAAAACCGCGCTGTGAGGCTGCGTTTCATTGGTTTGATGTCGTAAGGGATAGTGGGAACTTTGCGGGCTAATACTGTGGTCAACCAGTAACCGACGACCCAGCAGCTAATTAATTATTGATATTTTTCGCTATTCGTTTCATTCACGGGAGAAGGCAACGGATCAAGGGCGCGAGATTCAGCCGCAGTCCATAAGTACCCGGGAGCCCCAGCGCGGAAATGTGTTTTTCTCGCGTTAACATAGTTAAGACCCCTCAGCAACTCATGCGTCTTCGATTATCACGAGTAAGGAAAATGCCGCCAAATTGAAACCGATTGGCCTTGAGAGTCCCTTGCAAAGCTGGCAACCGAGAGTCAAATTGTACCATTCGTATTCAAGGGGGGCGTCTGGATCAAGACTCCTCGTACTTCACTCGAAGCTGTAAAGGACGGGGTGAGTATCCATACCGAAGCCGAAGCCCTTTACAAAGCAAGGAAACATTTTACCCCCCTGTCGGGGGGGTCCGCCTTAGCCCGTAATTTCTGCCTGCCCGGGCCGTTGCCACTGCTCGCCTCTGTTGTTAGTAGATCTTATCTTAGGTTTTGGTCGATGGGTTTTGGCCGGCGGTCACAGTAGCCTAGTGTATAGGTGAAGTGTCGTATATCGATTAGCGTGGGTACCAGATCTGTCCATACCCTAGGAGTTATACACCCACGGATCTGCGACATCAAACATACTTATTATCAGCGACAACCGAAAGTGCGAAATCCGAGACCTACCACTGCACAGCTCTTACCTGCTTTAGTAAATAATATTTCACTGATCTTTCAGGGGAATCTGCACAAGACGCGGGGGAGGACCATGAGATGATCCAATTACTCGGTAGAGGTAGGGACCACTAGCTG'
def tran(s,t):
    transt = 0
    transv = float(0)
    for nt in xrange(len(seq1)):
        if seq1[nt] == seq2[nt]:
            continue
        elif seq1[nt] == "A" and (seq2[nt] == "C" or seq2[nt] == "T"):
            transv += 1
        elif seq1[nt] == "G" and (seq2[nt] == "C" or seq2[nt] == "T"):
            transv += 1
        elif seq1[nt] == "C" and (seq2[nt] == "A" or seq2[nt] == "G"):
            transv += 1
        elif seq1[nt] == "T" and (seq2[nt] == "A" or seq2[nt] == "G"):
            transv += 1
        else:
            transt += 1
    ratio = transt / transv
    return ratio

print(tran(seq1,seq2))