a = 'CACGCCTGGCAACGTTTCACGAACTTGGTCTCCCTAATGATTGGAGTCTCAGGTGGGACTTGCTAATTGGACGCGTTCATGGGAGACGGAGAGCGCCTCGAGATATGTTTGCCTACGCCGTTTAGCCATTAGGCCGGACTGCGTACTTGACGGACCAATCGTGCGTGAGCCAAATGTGTTCTCGCCCCCTTGAACTAAAGATCTGACCTCTGCGACGCCGCTCACTCCCCTGACCACACTAACATAAGCGGGACAAAGTCTACACGCGAAAACGTGGGTTTAATAATTGACAATCCTACATGTGGTCAGACAGGGACGTTCTCGTGCGAGGCAACCTTTGGGTTTTGACGACGCTTGCAATTGCTGTGCACGCTAATCGTATGGGCGTAGATCGTTCGGCTTTTACGGTCTATGCCTATGGTCACAACTGTGTTAAACACCACAGCTTGGTGCCGAGTCCATTAGTCTCCAGCTGCACCAAGTATGGACCTTCTTTAGTCTTATTGCGTCGTACGAGATGATCGCAAGTTCCAGGAGTTTGTCTATCGTCCTGTGGATCGCGGGTGACGTGCCCAATTGTGTCTTACCCACACAACTCCATAATGAGGGCTCTCAATGCAGACTCTGCACCGCGGCAGGACGTCAATGAACTTTGTACAGGGCGACGACCTTGAAGCTCCTTCAGGGGCCCGTTACTGGCGCCGACACTTTGATATAAATAAGAGGTTCCCACGTGGAGCCAAGTAACAGTACTGTCGATTCGACCGCGTTGCCAGCGTTTGCCTCTGGGTCTAGCAGATGCCACAGTGACAGACTCGCCCGCGCAAGAAAAGAGGATTTCAGCGCTACCGAACGGTGGTATCTAGGGACTAGCTACACTCCGCTCGATGGATTCAAGGGATAGATCATTCCCGCTGACCGGGCCAGGAAAGTCGGTATCCATAGCTGTCAGTCTCCGACGAGGTGAGCGAAGGACTTTGTACT'

def dna_into_rna(a):
    b=''
    r=[]
    for letter in a:
        if not letter == 'T':
            r.append(letter)
        else:
            r.append('U')
    return b.join(r)


print(dna_into_rna(a))