s='TAATGTTTAATGTTCACTAATGTTCATAATGTTTTAATGTTACAAGTCTAATGTTGGTTTTAATGTTTAATGTTTTTAATGTTTAATGTTTAATGTTATAATGTTGCGCCTAATGTTAATAATGTTTAATGTTTTAATGTTTATAATGTTTAATGTTCCATCTAATGTTTAATGTTATAATGTTTTAATGTTCTAATGTTTTAATGTTTAATGTTATAATGTTTAATGTTCTAATGTTGTGACTAATGTTCAGCGCTAATGTTATTCTAATGTTGCGATAATGTTTAATGTTATTTAATGTTATAATGTTATAATGTTTTAATGTTCCCTAATGTTTTAATGTTGCTAATGTTTTAATGTTCCTCTTTGTTAATGTTCTAATGTTATCTAATGTTATAATGTTATAATGTTTCTAATGTTATAATGTTTAATGTTACCTAATGTTTAATGTTTAATGTTGTTAATGTTGCAGTAATGTTATAATGTTATTGGATAATGTTGGTAATAATGTTTGAGGTAATGTTATAATGTTTAATGTTTCCTATAATGTTTAATGTTCATAATGTTCCTTATCATAATGTTAATAATGTTACGACATAATGTTCGATTAATGTTGTTAATGTTTAATGTTCGTAATGTTTAATGTTTAATGTTTAATGTTTTAATGTTTAATGTTTAATGTTATTAATGTTTATAATGTTTAATGTTGTAATGTTTTGATTTGATAATGTTGTACTTAATGTTTACCTAATGTTCGCGAAGTAATGTTTAATGTTAGTAATGTTGTAATGTTTAATTAATGTTCCGGTTGCTAATGTT'
t='TAATGTTTA'
def count_pos_sub(s,t):
    k= len(t)
    lst=[]
    j=0
    while k < len(s) and j < (len(s)-(len(t))):
        if t in s[j:k]:
          lst.append((j+1))
        j+=1
        k+=1
    return ' '.join(map(str,lst))

print(count_pos_sub(s,t))



